package com.umain.draugr.vm

import com.umain.draugr.catalog.MachineSpec
import com.umain.draugr.catalog.UiKind

/**
 * TinyEMU is configured by a file it fetches itself, so the app generates one per machine and
 * serves it from the loopback server. Asset references are absolute URLs against that same
 * server, which is what turns the guest's block reads into HTTP Range requests.
 *
 * The format is TinyEMU's own relaxed JSON: unquoted keys, trailing commas allowed.
 */
object TinyEmuConfig {

    fun machineName(cpu: String): String = when (cpu) {
        "riscv64" -> "riscv64"
        "riscv32" -> "riscv32"
        "x86_64" -> "pc"
        else -> cpu
    }

    fun defaultCmdline(spec: MachineSpec): String = when (spec.ui) {
        UiKind.CONSOLE, UiKind.VGA_TEXT ->
            "loglevel=3 swiotlb=1 console=hvc0 root=/dev/vda rw"

        UiKind.X_WINDOW, UiKind.GRAPHICAL ->
            "loglevel=3 swiotlb=1 console=hvc0 root=/dev/vda rw fbcon=map:0"
    }

    fun render(spec: MachineSpec, serverOrigin: String): String {
        fun url(path: String?) = path?.let { "$serverOrigin/$it" }

        val lines = mutableListOf<String>()
        lines += "/* generated by draugr for ${spec.id}, do not edit */"
        lines += "{"
        lines += "  version: 1,"
        lines += "  machine: \"${machineName(spec.cpu)}\","
        lines += "  memory_size: ${spec.memMb},"
        url(spec.assets.bios)?.let { lines += "  bios: \"$it\"," }
        url(spec.assets.kernel)?.let { lines += "  kernel: \"$it\"," }
        url(spec.assets.initrd)?.let { lines += "  initrd: \"$it\"," }
        lines += "  cmdline: \"${defaultCmdline(spec)}\","
        url(spec.assets.hda)?.let { lines += "  drive0: { file: \"$it\" }," }
        if (spec.ui == UiKind.X_WINDOW || spec.ui == UiKind.GRAPHICAL) {
            lines += "  display0: { device: \"simplefb\", width: 1024, height: 768 },"
        }
        lines += "}"
        return lines.joinToString("\n") + "\n"
    }

    /** Path the config is served under, relative to the server root. */
    fun pathFor(spec: MachineSpec): String = "config/${spec.id}.cfg"
}
